"""Shared constants for the Sloth.ai scoring engine."""

from __future__ import annotations

__version__ = "0.1.0"

# Opportunity score weights (must sum to 90 before risk subtraction; max 100).
OPPORTUNITY_WEIGHT_REPETITION = 30
OPPORTUNITY_WEIGHT_MANUAL_EFFORT = 25
OPPORTUNITY_WEIGHT_CONSISTENCY = 20
OPPORTUNITY_WEIGHT_DATA_AVAILABILITY = 15
OPPORTUNITY_WEIGHT_RISK = 10

# Forecast scenario multipliers.
FORECAST_CONSERVATIVE_FACTOR = 0.7
FORECAST_OPTIMISTIC_FACTOR = 1.2

# Effectiveness dimension weights (sum to 100).
EFFECTIVENESS_WEIGHT_REALISED_TIME = 30
EFFECTIVENESS_WEIGHT_COVERAGE = 20
EFFECTIVENESS_WEIGHT_RELIABILITY = 20
EFFECTIVENESS_WEIGHT_QUALITY = 15
EFFECTIVENESS_WEIGHT_CYCLE_TIME = 10
EFFECTIVENESS_WEIGHT_ACCEPTANCE = 5
EFFECTIVENESS_SAFETY_CAP = 40

# Cursor Cloud Agents defaults (override via environment).
DEFAULT_CURSOR_MODEL = "composer-2.5"
DEFAULT_CURSOR_TIMEOUT_SECONDS = 120
DEFAULT_CURSOR_POLL_INTERVAL_SECONDS = 2.0

# Background inbox watcher (IMAP / upload / demo).
DEFAULT_INBOX_POLL_INTERVAL_SECONDS = 120
